name: Inox dev

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.legal/**'
      - '**/*.md'
      - 'jsconfig.json'
permissions: write-all

jobs:

  cleanup-prev-dev-assets:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
     - name: Delete old release assets
       uses: GraphR00t/delete-release-assets@v1
       with:
          token: ${{ github.token }}
          tag: dev
          fail-if-no-assets: false
          assets: "*"

  release-dev-linux-amd64:
    name: release dev linux/amd64
    needs: cleanup-prev-dev-assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: GraphR00t/go-release-action@v1.41
      with:
        # same as prod
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: "./cmd/inox"
        binary_name: "inox"
        extra_files: LICENSE README.md docs examples
        md5sum: false
        sha256sum: true
        # -----------------
        release_tag: dev
        overwrite: true

